// src/services/mockData.js
// Static movie data for frontend development (Day 02)

export const MOCK_USERS = {
  'john@example.com': {
    id: 'usr_a1b2c3d4',
    username: 'john_doe',
    email: 'john@example.com',
    password: 'Pass@123',
    fullName: 'John Doe',
    role: 'USER',
    avatar: null,
    createdAt: '2026-06-01T08:00:00Z',
    reviewCount: 12,
    watchlistCount: 5,
  },
};

export const MOCK_MOVIES = [
  {
    id: 'mov_001',
    title: 'Inception',
    tagline: 'Your mind is the scene of the crime',
    overview:
      'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O., but his tragic past may doom the project and his team to disaster.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    genres: ['Sci-Fi', 'Action', 'Thriller'],
    releaseDate: '2010-07-16',
    runtime: 148,
    rating: 8.8,
    reviewCount: 2340,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    cast: [
      { name: 'Leonardo DiCaprio', character: 'Dom Cobb' },
      { name: 'Joseph Gordon-Levitt', character: 'Arthur' },
      { name: 'Elliot Page', character: 'Ariadne' },
    ],
  },
  {
    id: 'mov_002',
    title: 'The Dark Knight',
    tagline: 'Why so serious?',
    overview:
      'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest psychological and physical tests of his ability to fight injustice.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911BTUgMe1nNaD3.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg',
    genres: ['Action', 'Crime', 'Drama'],
    releaseDate: '2008-07-18',
    runtime: 152,
    rating: 9.0,
    reviewCount: 3100,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    cast: [
      { name: 'Christian Bale', character: 'Bruce Wayne / Batman' },
      { name: 'Heath Ledger', character: 'The Joker' },
      { name: 'Aaron Eckhart', character: 'Harvey Dent' },
    ],
  },
  {
    id: 'mov_003',
    title: 'Interstellar',
    tagline: 'Mankind was born on Earth. It was never meant to die here.',
    overview:
      "Earth's future has been riddled by disasters, famines, and droughts. There is only one way to ensure mankind's survival: Interstellar travel.",
    posterUrl: 'https://image.tmdb.org/t/p/w500/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xJHokMbljvjADYdit5fK1DVfjko.jpg',
    genres: ['Sci-Fi', 'Adventure', 'Drama'],
    releaseDate: '2014-11-07',
    runtime: 169,
    rating: 8.7,
    reviewCount: 1890,
    certification: 'PG-13',
    director: 'Christopher Nolan',
    cast: [
      { name: 'Matthew McConaughey', character: 'Cooper' },
      { name: 'Anne Hathaway', character: 'Brand' },
      { name: 'Jessica Chastain', character: 'Murph' },
    ],
  },
  {
    id: 'mov_004',
    title: 'Parasite',
    tagline: 'Act like you own the place.',
    overview:
      'Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg',
    genres: ['Thriller', 'Comedy', 'Drama'],
    releaseDate: '2019-05-30',
    runtime: 132,
    rating: 8.5,
    reviewCount: 1560,
    certification: 'R',
    director: 'Bong Joon-ho',
    cast: [
      { name: 'Song Kang-ho', character: 'Ki-taek' },
      { name: 'Lee Sun-kyun', character: 'Park Dong-ik' },
      { name: 'Cho Yeo-jeong', character: 'Yeon-gyo' },
    ],
  },
  {
    id: 'mov_005',
    title: 'Dune: Part Two',
    tagline: 'Long live the fighters.',
    overview:
      'Paul Atreides unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/1pdfLvkbY9ohJlCjQH2CZjjYVvJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/xOMo8BRK7PfcJv9JCnx7s5hj0PX.jpg',
    genres: ['Sci-Fi', 'Adventure'],
    releaseDate: '2024-03-01',
    runtime: 166,
    rating: 8.6,
    reviewCount: 980,
    certification: 'PG-13',
    director: 'Denis Villeneuve',
    cast: [
      { name: 'Timothée Chalamet', character: 'Paul Atreides' },
      { name: 'Zendaya', character: 'Chani' },
      { name: 'Austin Butler', character: 'Feyd-Rautha' },
    ],
  },
  {
    id: 'mov_006',
    title: 'Spider-Man: Across the Spider-Verse',
    tagline: 'It\'s how you wear the mask that matters.',
    overview:
      'Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its very existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    genres: ['Animation', 'Action', 'Adventure'],
    releaseDate: '2023-06-02',
    runtime: 140,
    rating: 8.7,
    reviewCount: 1420,
    certification: 'PG',
    director: 'Joaquim Dos Santos',
    cast: [
      { name: 'Shameik Moore', character: 'Miles Morales' },
      { name: 'Hailee Steinfeld', character: 'Gwen Stacy' },
      { name: 'Oscar Isaac', character: 'Miguel O\'Hara' },
    ],
  },
  {
    id: 'mov_007',
    title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    overview:
      'The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/nb3xI8XI3w4pMVZ38VijceceOo6.jpg',
    genres: ['Drama', 'History', 'Thriller'],
    releaseDate: '2023-07-21',
    runtime: 180,
    rating: 8.4,
    reviewCount: 2100,
    certification: 'R',
    director: 'Christopher Nolan',
    cast: [
      { name: 'Cillian Murphy', character: 'J. Robert Oppenheimer' },
      { name: 'Emily Blunt', character: 'Kitty Oppenheimer' },
      { name: 'Robert Downey Jr.', character: 'Lewis Strauss' },
    ],
  },
  {
    id: 'mov_008',
    title: 'Everything Everywhere All at Once',
    tagline: 'The universe is so much bigger than you realize.',
    overview:
      'A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes and connecting with the lives she could have led.',
    posterUrl: 'https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/original/feSiISwgEpVzR1v3zv2n2AU4ANJ.jpg',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    releaseDate: '2022-03-25',
    runtime: 139,
    rating: 8.0,
    reviewCount: 1750,
    certification: 'R',
    director: 'Daniel Kwan',
    cast: [
      { name: 'Michelle Yeoh', character: 'Evelyn Wang' },
      { name: 'Ke Huy Quan', character: 'Waymond Wang' },
      { name: 'Jamie Lee Curtis', character: 'Deirdre Beaubeirdre' },
    ],
  },
];

export const MOCK_GENRES = [
  'Action',
  'Adventure',
  'Animation',
  'Comedy',
  'Crime',
  'Drama',
  'History',
  'Sci-Fi',
  'Thriller',
];

export const MOCK_REVIEWS = [
  {
    id: 'rev_001',
    movieId: 'mov_001',
    user: { id: 'usr_a1b2c3d4', username: 'john_doe', avatar: null },
    rating: 9,
    title: 'A Masterpiece of Modern Cinema',
    content: 'Nolan outdoes himself with this mind-bending thriller that challenges the audience to question the nature of reality. The visual effects are groundbreaking and the story is endlessly rewatchable.',
    containsSpoilers: false,
    helpfulCount: 45,
    createdAt: '2026-06-10T14:30:00Z',
  },
  {
    id: 'rev_002',
    movieId: 'mov_001',
    user: { id: 'usr_b2c3d4e5', username: 'cinema_fan', avatar: null },
    rating: 8,
    title: 'Brilliant but demands attention',
    content: 'Not a movie you can watch casually. You need to pay attention to every detail. The layered dream sequences are genius but can be confusing on first watch.',
    containsSpoilers: false,
    helpfulCount: 23,
    createdAt: '2026-06-09T10:15:00Z',
  },
  {
    id: 'rev_003',
    movieId: 'mov_002',
    user: { id: 'usr_c3d4e5f6', username: 'dark_knight_rises', avatar: null },
    rating: 10,
    title: 'The definitive superhero film',
    content: 'Heath Ledger\'s performance as the Joker is one of the greatest in cinema history. This film transcends the superhero genre entirely.',
    containsSpoilers: false,
    helpfulCount: 89,
    createdAt: '2026-06-08T20:45:00Z',
  },
];
